name: Deploy Portfolio
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
      NEXT_TELEMETRY_DISABLED: ${{ secrets.NEXT_TELEMETRY_DISABLED }}

    steps:
      - name: üå¥ Checkout code
        uses: actions/checkout@v4

      - name: üß∞ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Install dependencies
        run: npm ci

      - name: üß© Install missing native binaries
        run: |
          npm install @parcel/css-linux-x64-gnu
          npm install @ast-grep/napi-linux-x64-gnu

      - name: üîß Rebuild lightningcss native binary
        run: npm rebuild lightningcss

      - name: üó£Ô∏è Generate Cloudflare types
        run: npm run cf-typegen

      - name: üõ†Ô∏è Build the Next.js app
        run: npm run build-deploy

      - name: üöÄ Set Wrangler Secrets
        run: |
          echo "${{ secrets.JWT_SECRET }}" | npx wrangler secret put JWT_SECRET --yes
          echo "${{ secrets.SITE_PASSWORD }}" | npx wrangler secret put SITE_PASSWORD --yes
          echo "${{ secrets.NEXT_TELEMETRY_DISABLED }}" | npx wrangler secret put NEXT_TELEMETRY_DISABLED --yes
          echo "${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}" | npx wrangler secret put NEXT_PUBLIC_SANITY_PROJECT_ID --yes
          echo "${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}" | npx wrangler secret put NEXT_PUBLIC_SANITY_DATASET --yes

      - name: üöÄ Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        